services:
  app:
    ports:
      - 5000:5000
      - 5678:5678
    environment:
      - FLASK_APP=/app/app.py
    volumes:
      - ./app/src:/app
    command: ["./dbupgrade_and_run.sh", "sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5000"]
