"""agendaitem: add is_hidden, hidden_reason

Revision ID: 128c7e32169e
Revises: f9160c45895b
Create Date: 2020-08-26 13:51:07.531558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128c7e32169e'
down_revision = 'f9160c45895b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendaitem', sa.Column('hidden_reason', sa.Text(), nullable=True))
    op.add_column('agendaitem', sa.Column('is_hidden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendaitem', 'is_hidden')
    op.drop_column('agendaitem', 'hidden_reason')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

