"""Meeting location/time; Position has_status_report

Revision ID: 2a164fc330d0
Revises: a50e39caa48d
Create Date: 2020-08-11 15:53:37.461593

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.sql import table, column
from alembic import op

# revision identifiers, used by Alembic.
revision = '2a164fc330d0'
down_revision = 'a50e39caa48d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('meeting', sa.Column('time', sa.Time(), nullable=True))
    op.add_column('position', sa.Column('has_status_report', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # default position.has_status_report to True
    position = table('position',
                     column('has_status_report', sa.Boolean()))
    op.execute(
        position.update().\
            values({'has_status_report':op.inline_literal(True)})
    )

def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'has_status_report')
    op.drop_column('meeting', 'time')
    op.drop_column('meeting', 'location')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

