"""task completion by position (#383)

Revision ID: 2b0acf03881a
Revises: cacdee34a411
Create Date: 2022-06-07 14:55:51.486478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0acf03881a'
down_revision = 'cacdee34a411'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('isbyposition', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'position', ['position_id'], ['id'])
    op.add_column('taskcompletion', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'taskcompletion', 'position', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taskcompletion', type_='foreignkey')
    op.drop_column('taskcompletion', 'position_id')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'position_id')
    op.drop_column('task', 'isbyposition')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

