"""rt_application: add logtime, remove date

Revision ID: 300805031b51
Revises: 44de12a16a57
Create Date: 2022-01-25 14:59:56.897935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300805031b51'
down_revision = '44de12a16a57'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rt_application', sa.Column('logtime', sa.DateTime(), nullable=True))
    op.drop_column('rt_application', 'date')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rt_application', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('rt_application', 'logtime')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

