"""AgendaItem gets invite/action controls

Revision ID: 3716b668fbd6
Revises: 4e8e9b88e865
Create Date: 2020-07-11 05:16:43.981437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3716b668fbd6'
down_revision = '4e8e9b88e865'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendaitem', sa.Column('is_action_only', sa.Boolean(), nullable=False))
    op.add_column('agendaitem', sa.Column('is_attendee_only', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agendaitem', 'is_attendee_only')
    op.drop_column('agendaitem', 'is_action_only')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

