"""member table: remove start_time, end_time

Revision ID: 40d6c125c595
Revises: db3ffeebcb11
Create Date: 2023-12-05 15:20:46.721594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d6c125c595'
down_revision = 'db3ffeebcb11'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'end_date')
    op.drop_column('member', 'start_date')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('start_date', sa.DATE(), nullable=True))
    op.add_column('member', sa.Column('end_date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

