"""Meetings Module: automatic status report generation

Revision ID: 5f0bc492bb41
Revises: 6c091e0fbcbe
Create Date: 2020-11-04 12:36:29.454946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0bc492bb41'
down_revision = '6c091e0fbcbe'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussionitem', sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('meeting', sa.Column('last_status_gen', sa.DateTime(), nullable=True))
    op.add_column('statusreport', sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###

def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statusreport', 'update_time')
    op.drop_column('meeting', 'last_status_gen')
    op.drop_column('discussionitem', 'update_time')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

