"""meeting, localinterest: support g suite configuration for minutes, agenda, status report

Revision ID: 6c091e0fbcbe
Revises: e3c2bd975645
Create Date: 2020-09-24 15:56:28.138216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c091e0fbcbe'
down_revision = 'e3c2bd975645'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localinterest', sa.Column('gs_agenda_fdr', sa.Text(), nullable=True))
    op.add_column('localinterest', sa.Column('gs_minutes_fdr', sa.Text(), nullable=True))
    op.add_column('localinterest', sa.Column('gs_status_fdr', sa.Text(), nullable=True))
    op.add_column('meeting', sa.Column('gs_agenda', sa.Text(), nullable=True))
    op.add_column('meeting', sa.Column('gs_minutes', sa.Text(), nullable=True))
    op.add_column('meeting', sa.Column('gs_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'gs_status')
    op.drop_column('meeting', 'gs_minutes')
    op.drop_column('meeting', 'gs_agenda')
    op.drop_column('localinterest', 'gs_status_fdr')
    op.drop_column('localinterest', 'gs_minutes_fdr')
    op.drop_column('localinterest', 'gs_agenda_fdr')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

