"""Invite.invitekey is 32 characters

Revision ID: 8d85231f4d91
Revises: cb23d9bd7e18
Create Date: 2020-08-09 15:06:59.618043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d85231f4d91'
down_revision = 'cb23d9bd7e18'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invite', 'invitekey',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invite', 'invitekey',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

