"""meeting support - invite: add agendaitem

Revision ID: b1abd6e837d2
Revises: 4e95ae391320
Create Date: 2020-06-17 06:20:33.637533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1abd6e837d2'
down_revision = '4e95ae391320'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('agendaitem_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invite', 'agendaitem', ['agendaitem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invite', type_='foreignkey')
    op.drop_column('invite', 'agendaitem_id')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

