"""add club service and id to LocalInterest

Revision ID: b890ed51cfa6
Revises: 
Create Date: 2020-05-30 06:45:09.603828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b890ed51cfa6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localinterest', sa.Column('club_service', sa.String(length=32), nullable=True))
    op.add_column('localinterest', sa.Column('service_id', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('localinterest', 'service_id')
    op.drop_column('localinterest', 'club_service')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

