"""Meeting.time is now Text

Revision ID: b990f517f26f
Revises: 5f0bc492bb41
Create Date: 2020-11-05 06:34:26.962987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b990f517f26f'
down_revision = '5f0bc492bb41'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting', 'time',
               existing_type=mysql.VARCHAR(length=8),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meeting', 'time',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

