"""add awards_awardee.active

Revision ID: 081fea03103f
Revises: 3d10aac1f03d
Create Date: 2025-07-16 16:30:02.686283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081fea03103f'
down_revision = '3d10aac1f03d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('awards_awardee', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('awards_awardee', 'active')
    # ### end Alembic commands ###

