"""motion table: add mover, seconder

Revision ID: 28123029d4e6
Revises: cbac9afeaa40
Create Date: 2020-08-31 14:58:13.547101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28123029d4e6'
down_revision = 'cbac9afeaa40'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motion', sa.Column('mover_id', sa.Integer(), nullable=True))
    op.add_column('motion', sa.Column('seconder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'motion', 'localuser', ['seconder_id'], ['id'])
    op.create_foreign_key(None, 'motion', 'localuser', ['mover_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'motion', type_='foreignkey')
    op.drop_constraint(None, 'motion', type_='foreignkey')
    op.drop_column('motion', 'seconder_id')
    op.drop_column('motion', 'mover_id')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

