"""add system, systemaccesslevel, accesstype, positionaccessnotice tables and
position accesstypes/direct_access, for tracking systems required per
position (see #716)

Revision ID: 326ce70b31d1
Revises: 73938f9003e0
Create Date: 2026-08-22 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326ce70b31d1'
down_revision = '73938f9003e0'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['localinterest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('systemaccesslevel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['localinterest.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accesstype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['localinterest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accesstype_systemaccesslevel',
    sa.Column('accesstype_id', sa.Integer(), nullable=True),
    sa.Column('systemaccesslevel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accesstype_id'], ['accesstype.id'], ),
    sa.ForeignKeyConstraint(['systemaccesslevel_id'], ['systemaccesslevel.id'], )
    )
    op.create_table('position_accesstype',
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('accesstype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accesstype_id'], ['accesstype.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], )
    )
    op.create_table('position_directaccess',
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('systemaccesslevel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['systemaccesslevel_id'], ['systemaccesslevel.id'], )
    )
    op.create_table('positionaccessnotice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('accesslevel_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('grant', 'revoke'), nullable=False),
    sa.Column('reason_position_id', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accesslevel_id'], ['systemaccesslevel.id'], ),
    sa.ForeignKeyConstraint(['interest_id'], ['localinterest.id'], ),
    sa.ForeignKeyConstraint(['reason_position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['localuser.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['localuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positionaccessnotice')
    op.drop_table('position_directaccess')
    op.drop_table('position_accesstype')
    op.drop_table('accesstype_systemaccesslevel')
    op.drop_table('accesstype')
    op.drop_table('systemaccesslevel')
    op.drop_table('system')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
