"""add discoursereviewnotice table

Revision ID: 44975ae71024
Revises: 081fea03103f
Create Date: 2026-07-18 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44975ae71024'
down_revision = '081fea03103f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()




def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discoursereviewnotice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('reviewable_id', sa.Integer(), nullable=False),
    sa.Column('first_notified_at', sa.DateTime(), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['localinterest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interest_id', 'reviewable_id', name='uq_discoursereviewnotice_interest_reviewable')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discoursereviewnotice')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
