"""enhance StatusReport/MemberStatusReport, add DiscussionItem

Revision ID: a50e39caa48d
Revises: 8d85231f4d91
Create Date: 2020-08-10 15:44:00.679871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a50e39caa48d'
down_revision = '8d85231f4d91'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussionitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('discussiontitle', sa.String(length=128), nullable=True),
    sa.Column('agendaitem_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agendaitem_id'], ['agendaitem.id'], ),
    sa.ForeignKeyConstraint(['interest_id'], ['localinterest.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberstatusreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('invite_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_rsvp', sa.Boolean(), nullable=True),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['statusreport.id'], ),
    sa.ForeignKeyConstraint(['interest_id'], ['localinterest.id'], ),
    sa.ForeignKeyConstraint(['invite_id'], ['invite.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberstatusreport_discussionitem',
    sa.Column('memberstatusreport_id', sa.Integer(), nullable=True),
    sa.Column('discussionitem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discussionitem_id'], ['discussionitem.id'], ),
    sa.ForeignKeyConstraint(['memberstatusreport_id'], ['memberstatusreport.id'], )
    )
    op.add_column('statusreport', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'statusreport', 'position', ['position_id'], ['id'])
    op.drop_column('statusreport', 'order')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statusreport', sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'statusreport', type_='foreignkey')
    op.drop_column('statusreport', 'position_id')
    op.drop_table('memberstatusreport_discussionitem')
    op.drop_table('memberstatusreport')
    op.drop_table('discussionitem')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

