"""add meeting to motion vote

Revision ID: ad076ac6931b
Revises: 26ae315ec30d
Create Date: 2020-07-24 15:43:55.472692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad076ac6931b'
down_revision = '26ae315ec30d'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motionvote', sa.Column('meeting_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'motionvote', 'meeting', ['meeting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'motionvote', type_='foreignkey')
    op.drop_column('motionvote', 'meeting_id')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

