"""use LocalUserMixin

Revision ID: c621d93adf94
Revises: b1abd6e837d2
Create Date: 2020-06-22 16:46:26.240783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c621d93adf94'
down_revision = 'b1abd6e837d2'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localuser', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('localuser', sa.Column('given_name', sa.String(length=256), nullable=True))
    op.add_column('localuser', sa.Column('name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('localuser', 'name')
    op.drop_column('localuser', 'given_name')
    op.drop_column('localuser', 'email')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

