"""meeting shows action items since date

Revision ID: cb23d9bd7e18
Revises: ad076ac6931b
Create Date: 2020-07-31 06:02:38.161809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb23d9bd7e18'
down_revision = 'ad076ac6931b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actionitem', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('actionitem', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('meeting', sa.Column('show_actions_since', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'show_actions_since')
    op.drop_column('actionitem', 'updated_by')
    op.drop_column('actionitem', 'update_time')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

