"""add agendaitem.statusreport

Revision ID: f9160c45895b
Revises: 8a0d9359cfac
Create Date: 2020-08-16 12:19:40.332533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9160c45895b'
down_revision = '8a0d9359cfac'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agendaitem', sa.Column('statusreport_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agendaitem', 'statusreport', ['statusreport_id'], ['id'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agendaitem', type_='foreignkey')
    op.drop_column('agendaitem', 'statusreport_id')
    # ### end Alembic commands ###


def upgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_users():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

